# Numpy

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

What is an array
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
## initially Lets import numpy

import numpy as np


In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
type(a)


numpy.ndarray

In [4]:
a.ndim

1

In [8]:
###Numpy arrays can be created from Python lists or tuple in the following way.
import numpy as np
a = np.array([1, 2, 3])
type(a)
b = np.array((3, 4, 5))
type(b)

numpy.ndarray

In [10]:
x = np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
x = np.zeros((2,3,4))
print(x)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [12]:
np.zeros(3)


array([0., 0., 0.])

In [15]:
x = np.zeros((3,4))  
print(x)
type(x.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


numpy.dtype

In [16]:
x.shape

(3, 4)

In [17]:
y = np.ones( (3,4), dtype=np.float64 )  
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
print(x.dtype)
print(y.dtype)

float64
float64


In [19]:
np.full( (3,4), 0.11)

array([[0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11]])

In [20]:
np.full( (3,4), np.pi )

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [21]:
# start from 1 arrugment to 2nd arrugment in the  gap of 3rd arrugment
np.arange( 10, 30, 2 )

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [23]:
#arange genrate the numbers in np
np.arange( 10, 30,)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [24]:
%timeit np.arange(1, 100, 0.1)

1.76 µs ± 18.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [25]:
np.arange( 0, 2, 0.5 )

array([0. , 0.5, 1. , 1.5])

In [26]:
np.arange( 0, 20, 0.005 ).shape

(4000,)

In [27]:
x = [
        [
            1,2,3,4
        ],
        [
            1,2,2,2
        ]
]
x1 = np.array(x)
print(x1.shape)

(2, 4)


In [28]:
three_d_array = np.full((2,3,4), 0.11)

In [29]:
three_d_array.size

24

In [30]:
three_d_array.reshape(-1, 6)

array([[0.11, 0.11, 0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11, 0.11, 0.11]])

In [31]:
three_d_array.shape

(2, 3, 4)

In [32]:
x = [
        [
            [1, 3],
            [1, 3], 
            [1, 3],
            [1, 3]
        ],
#         [
#             [1, 3],
#             [1, 3], 
#             [1, 3],
#             [1, 3]
#         ]
]

In [33]:
xx = np.array(x)
print(xx.shape)
print(xx)

(1, 4, 2)
[[[1 3]
  [1 3]
  [1 3]
  [1 3]]]


In [34]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [35]:
np.linspace(0, 10, 50)


array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [36]:
np.linspace(0, 5/3, 6)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667])

no of dimension in a dataset having list of pictures.

* First: # of pics
* Second: x axis
* Third: y axis
* Forth: r, g, b

In [37]:
# Make a 2x3 matrix having random floats between 0 and 1:
x = np.random.rand(2,3)

In [38]:
x = np.empty((2,3))

In [39]:
x

array([[4.67005114e-310, 6.90261622e-310, 6.90260833e-310],
       [6.90260833e-310, 6.90261027e-310, 6.90261644e-310]])

In [40]:
x.ndim

2

In [41]:
x.shape

(2, 3)

In [42]:
x.size

6

In [43]:
x

array([[4.67005114e-310, 6.90261622e-310, 6.90260833e-310],
       [6.90260833e-310, 6.90261027e-310, 6.90261644e-310]])

In [44]:
x[0]

array([4.67005114e-310, 6.90261622e-310, 6.90260833e-310])

In [45]:
x[1]

array([6.90260833e-310, 6.90261027e-310, 6.90261644e-310])

In [46]:
x[1][0]

6.9026083315096e-310

In [47]:
x[1,0]

6.9026083315096e-310

In [48]:
c = np.arange(1, 5)

In [49]:
c

array([1, 2, 3, 4])

In [50]:
c.dtype

dtype('int64')

In [51]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [52]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [53]:
a = np.arange(24)
print(a)
b = a.reshape(2,3,4)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [54]:
b.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [55]:
#  2x4 array filled with numbers between 0 to 2
a = np.random.rand(2,4)*10

In [56]:
a

array([[9.37231058, 7.08655038, 1.871176  , 6.11394555],
       [8.26670403, 3.85666392, 7.63726874, 0.32514353]])

In [57]:
a = np.arange(50)
print(a)
print(a.reshape(-1, 5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [58]:
#np.RAISE?

In [59]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [60]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [61]:
a = np.arange(24)

In [62]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [63]:
a[17]

17

In [64]:
a[5:7]

array([5, 6])

In [65]:
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [66]:
a[:10:2]

array([0, 2, 4, 6, 8])

In [67]:
a[:10:-1]

array([23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [68]:
print(a[2::2])

[ 2  4  6  8 10 12 14 16 18 20 22]


In [69]:
print(a[2::3])

[ 2  5  8 11 14 17 20 23]


In [70]:
print(a[::-1])

[23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [71]:
print(a[::-3])

[23 20 17 14 11  8  5  2]


In [72]:
a = np.array([1, 5, 3, 19, 13, 7, 3])
print(a)
a[1:3] = -1
print(a)

[ 1  5  3 19 13  7  3]
[ 1 -1 -1 19 13  7  3]


In [73]:
b = [1, 2, 5, 7, 8]

In [74]:
a = np.array([1, 2, 5, 7, 8])
a

array([1, 2, 5, 7, 8])

In [75]:
a_slice = a[1:5] # 2, 5, 7, 8
a_slice

array([2, 5, 7, 8])

In [76]:
a_slice[1] = 1000
a_slice

array([   2, 1000,    7,    8])

In [77]:
a

array([   1,    2, 1000,    7,    8])

In [78]:
a_slice_copy = a_slice.copy()
a_slice_copy[3] = 800
a_slice_copy

array([   2, 1000,    7,  800])

In [79]:
print(a)
print(a_slice)

[   1    2 1000    7    8]
[   2 1000    7    8]


In [80]:
another_slice = a[2:6].copy()
another_slice[1] = 23333  
print(another_slice) #Updated
print(a) #Unchanged

[ 1000 23333     8]
[   1    2 1000    7    8]


In [81]:
x = np.array([1,2])
y = np.array([[2, 3], [4,5]])

In [82]:
y[0] = x

In [83]:
y[1] = x

In [84]:
y

array([[1, 2],
       [1, 2]])

In [85]:
x[0] = 100

In [86]:
y

array([[1, 2],
       [1, 2]])

In [87]:
a + a/2.9

array([   1.34482759,    2.68965517, 1344.82758621,    9.4137931 ,
         10.75862069])

In [88]:
x = np.random.rand(4,5)

In [89]:
x

array([[0.11559786, 0.78312437, 0.3381246 , 0.53009247, 0.83856654],
       [0.99515557, 0.63229854, 0.14014642, 0.50996582, 0.8459945 ],
       [0.42040642, 0.20184701, 0.65550848, 0.08413446, 0.75922696],
       [0.38613868, 0.91541555, 0.60208863, 0.0420575 , 0.41786174]])

In [90]:
x[1]

array([0.99515557, 0.63229854, 0.14014642, 0.50996582, 0.8459945 ])

In [91]:
print(x[1][1])
print(x[1, 1])

0.6322985403139804
0.6322985403139804


In [92]:
x[0:2, 0:2]

array([[0.11559786, 0.78312437],
       [0.99515557, 0.63229854]])

In [93]:
x = np.random.rand(3, 3, 3)

In [94]:
x

array([[[0.83549846, 0.62414591, 0.58611489],
        [0.28934876, 0.12129401, 0.46693106],
        [0.55537214, 0.8475921 , 0.48891418]],

       [[0.15791149, 0.51048354, 0.68468588],
        [0.94777116, 0.97537707, 0.36968068],
        [0.30645119, 0.99155295, 0.9105921 ]],

       [[0.95171781, 0.89232284, 0.6790681 ],
        [0.78577644, 0.89253399, 0.23392625],
        [0.75241022, 0.52185913, 0.18614987]]])

In [95]:
x[0:2, 0:2, 1:3]


array([[[0.62414591, 0.58611489],
        [0.12129401, 0.46693106]],

       [[0.51048354, 0.68468588],
        [0.97537707, 0.36968068]]])

In [96]:
x[1:4:2, 0:2, 0:3]

array([[[0.15791149, 0.51048354, 0.68468588],
        [0.94777116, 0.97537707, 0.36968068]]])

In [97]:
a = np.arange(12).reshape(3, -1)

In [98]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
rows_on = np.array([ True, False, True])

In [100]:
rows_on


array([ True, False,  True])

In [101]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
a[rows_on]


array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [103]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [104]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
a[[True, False, True]]


array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [106]:
a[:,[True, False, True, False]]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [107]:
x = np.random.rand(5,3)
print(x)

[[0.83803167 0.79195902 0.67107015]
 [0.45446465 0.80315313 0.22794075]
 [0.24214527 0.84989314 0.53231196]
 [0.84680415 0.60536358 0.17286086]
 [0.12519368 0.7517788  0.98570459]]


In [108]:
x[-1, 1]

0.7517787986029311

In [109]:
x[:,2]


array([0.67107015, 0.22794075, 0.53231196, 0.17286086, 0.98570459])

In [110]:
x[2:4, 1]


array([0.84989314, 0.60536358])

In [111]:
x

array([[0.83803167, 0.79195902, 0.67107015],
       [0.45446465, 0.80315313, 0.22794075],
       [0.24214527, 0.84989314, 0.53231196],
       [0.84680415, 0.60536358, 0.17286086],
       [0.12519368, 0.7517788 , 0.98570459]])

Create a 2d array such that it has 5 rows and only 1 column having values of last column



In [112]:
y = x[:,2].reshape(-1, 1)


In [113]:
y.shape


(5, 1)

In [114]:
p = np.arange(10)
print(p)

[0 1 2 3 4 5 6 7 8 9]


In [115]:
p[2:8:3]


array([2, 5])

In [116]:
x[2:3:1, :]


array([[0.24214527, 0.84989314, 0.53231196]])

In [118]:
a = np.array([[2,4]])
print(a.shape)
b = np.array([1,5])
print(b.shape)
c = a+b
print(c.shape)

(1, 2)
(2,)
(1, 2)


In [119]:
a = np.array( [20, 30, 40, 50] )
b = np.arange( 4 )
print(a)
print(b)
c = a + b
print(c)

[20 30 40 50]
[0 1 2 3]
[20 31 42 53]


In [120]:
d= []
for i in range(a.size):
    d.append(a[i] + b[i])
print(d)

[20, 31, 42, 53]


In [123]:
c = a - b
c

array([20, 29, 38, 47])

In [124]:
A = np.array( [[1,1],
               [0,1]] )

B = np.array( [[2,0],
               [3,4]] )
print(A*B)                         # element wise product

print([[1*2, 1*0],
       [0*3, 1*4]])

[[2 0]
 [0 4]]
[[2, 0], [0, 4]]


In [125]:
print(np.dot(A, B))
print([[1*2+ 1*3, 1*0+ 1*4],
       [0*2+1*3, 0*0+1*4]])

[[5 4]
 [3 4]]
[[5, 4], [3, 4]]


In [126]:
# np.arange - Creating sequence of Numbers

a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
c = a / b
print(c)

[20.         15.         13.33333333 12.5       ]


In [127]:
np.power(a, b)

array([     20,     900,   64000, 6250000])

In [128]:
c

array([20.        , 15.        , 13.33333333, 12.5       ])

In [129]:
a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
c = a // b
c

array([20, 15, 13, 12])

In [130]:
#Modulus operator can be applied on NumPy arrays as shown below. They apply element wise.
a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
c = a % b
c

array([0, 0, 1, 2])

In [131]:
a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
c = a ** b
c

array([     20,     900,   64000, 6250000])

In [132]:
m = np.array([20, -5, 30, 40])
m < [15, 16, 35, 36]

array([False,  True,  True, False])

In [133]:
m < 25

array([ True,  True, False, False])

In [134]:
m[m < 25]

array([20, -5])

In [135]:
h = np.arange(5).reshape(1, 1, 5)
print(h)
print(h.shape)

[[[0 1 2 3 4]]]
(1, 1, 5)


In [136]:
b = np.array([10, 20, 30, 40, 50])
b.reshape(1,1,5)

array([[[10, 20, 30, 40, 50]]])

In [137]:
x = h + [10, 20, 30, 40, 50]
print(x)
print(x.shape)

[[[10 21 32 43 54]]]
(1, 1, 5)


In [138]:
h + [[[10, 20, 30, 40, 50]]]

array([[[10, 21, 32, 43, 54]]])

In [139]:
h + b.reshape(1,1,5)

array([[[10, 21, 32, 43, 54]]])

In [140]:
k = np.arange(6).reshape(2, 3)

In [141]:
k

array([[0, 1, 2],
       [3, 4, 5]])

In [142]:
k + [100, 200, 300]

array([[100, 201, 302],
       [103, 204, 305]])

In [144]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
print("mean =", a.mean())

mean = 6.766666666666667


In [145]:
np.prod(a)

-71610.0

In [146]:
print(-2.5* 3.1* 7*10*11*12)

-71610.0


In [147]:
import math
a = np.array([1,3,4])
m = np.mean(a)
print(m)
print(a -m)
x = (a-m)**2
print(x)
s = np.sum(x)
print(s)
v = np.var(a)
print(v)
print(v*len(a))
print(np.std(a))
print(math.sqrt(s/len(a)))

2.6666666666666665
[-1.66666667  0.33333333  1.33333333]
[2.77777778 0.11111111 1.77777778]
4.666666666666666
1.5555555555555554
4.666666666666666
1.247219128924647
1.247219128924647


In [148]:
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [149]:
c.sum(axis=0)  # sum across matrices

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [150]:
import numpy as np
a = np.array([[10,20],[30,40]])
b = np.array([1])
print(a+b)

[[11 21]
 [31 41]]


In [151]:
import numpy as np
import pandas as pd

In [152]:
weights = {"alice": 68, "bob": 83, "colin": 86, "darwin": 68}

In [153]:
weights

{'alice': 68, 'bob': 83, 'colin': 86, 'darwin': 68}

In [154]:
s3 = pd.Series(weights)

In [155]:
s3 + s3

alice     136
bob       166
colin     172
darwin    136
dtype: int64

In [157]:
a = np.array([[1, 2, 3],
[4, 5, 6]])
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [158]:
a.sum(axis=0)

array([5, 7, 9])

In [159]:
a.sum(axis=1)

array([ 6, 15])

In [160]:
b = np.array([[.1, .2, .3],
[.4, .5, .6]])

In [161]:
from numpy import linalg

In [162]:
coeffs  = np.array([[2, 6], [5, 3]])
depvars = np.array([6, -9])
solution = linalg.solve(coeffs, depvars)

In [163]:
solution

array([-3.,  2.])

In [164]:
coeffs.dot(solution)

array([ 6., -9.])